ghost:
  build: .
  volumes:
   - ./content/data:/ghost-override/content/data
   - ./content/images:/ghost-override/content/images
  ports:
   - "8001:2368"
  environment:
    - BLOG_URL=blog.thejsj.com